import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: [
    "eslint",
    "import",
    "jsdoc",
    "jsx-a11y",
    "nextjs",
    "node",
    "oxc",
    "promise",
    "react",
    "react-perf",
    "typescript",
    "unicorn",
    "vitest",
  ],
  jsPlugins: ["@stylistic/eslint-plugin"],
  categories: {
    correctness: "warn",
    suspicious: "warn",
    perf: "warn",
  },
  rules: {
    curly: "deny",
    eqeqeq: ["deny", "always", { null: "ignore" }],
    "no-console": "warn",
    "no-debugger": "deny",
    "prefer-const": "deny",
    "typescript/no-explicit-any": "warn",
    "typescript/consistent-type-imports": "deny",
    "import/no-cycle": "deny",
    "import/no-self-import": "deny",
    "import/no-unassigned-import": ["deny", { allow: ["**/*.css"] }],
    "react/react-in-jsx-scope": "off",
    "unicorn/prefer-node-protocol": "deny",
    "@stylistic/lines-around-comment": [
      "error",
      {
        allowArrayStart: true,
        allowBlockStart: true,
        allowClassStart: true,
        allowEnumStart: true,
        allowInterfaceStart: true,
        allowModuleStart: true,
        allowObjectStart: true,
        allowTypeStart: true,
        beforeBlockComment: true,
      },
    ],
    "@stylistic/padding-line-between-statements": [
      "error",
      { blankLine: "always", next: "return", prev: "*" },
      { blankLine: "always", next: "*", prev: ["const", "let", "var"] },
      {
        blankLine: "any",
        next: ["const", "let", "var"],
        prev: ["const", "let", "var"],
      },
      { blankLine: "always", next: "*", prev: "directive" },
      { blankLine: "any", next: "directive", prev: "directive" },
      { blankLine: "always", next: "*", prev: ["case", "default"] },
      { blankLine: "always", next: "*", prev: "multiline-block-like" },
    ],
    "@stylistic/spaced-comment": ["error", "always"],
  },
  env: {
    builtin: true,
  },
  options: {
    typeAware: true,
  },
});
